version: '3.4'

services:
  wcpic:
    image: picture_worker
    container_name: picture_worker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:80
    volumes: 
      - ./tmp:/fast_app/tmp